allowBuilds:
  '@dryft/tlsclient': false
  '@prisma/engines': false
  ffmpeg-static: true
  prisma: false
  sharp: false
  unrs-resolver: false
patchedDependencies:
  '@dryft/tlsclient@1.0.8': patches/@dryft__tlsclient@1.0.8.patch
